### ISSUE TITLE
Unable to resolve module `react-native-iphone-x-helper`... : Module `react-native-iphone-x-helper`does not exist in the Haste module map

### ISSUE THREAD

**Issue by ninareunes** [WrathChaos/react-native-dynamic-vector-icons#11]
Hi 
I get the following error when trying to import the react-native-dynamic-search-bar. I am using expo but i'm really new to react native

![image](https://user-images.githubusercontent.com/44461009/69986000-b1987080-153c-11ea-96f3-4336ce7b7b48.png)

Could you please help? Thanks in advance

**Comment by WrathChaos** [comment]
Hello @ninareunes,
This issue is not related to this library. You need to install `react-native-iphone-x-helper` library with this command: 

`npm i react-native-iphone-x-helper`

Also, I believe that you want to use `react-native-dynamic-search-bar`. You need to use:
`npm i WrathChaos/react-native-dynamic-vector-icons#expo` to use it with Expo. 

If you're new on React Native, I suggest you **NOT** to use Expo, keep going with Pure React Native :)
